# An example of scheduled playbook
# This would be triggered
id: monthly-report
allow_concurrent: false
allow_multiple: false
target:
    table: users
    identifier: id
audience:
    - name: AllUsers
steps:
    - name: Send Monthly Report
      id: monthly-report
      actions:
          - type: Mail
            mailable: MonthlyReport
